import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:logger/logger.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'core/theme/app_theme.dart';
import 'core/utils/rwanda_location.dart';
import 'core/services/notification_service.dart';
import 'core/services/fcm_service.dart';
import 'core/providers/language_provider.dart';
import 'presentation/routes/app_router.dart';
import 'core/localization/rw_localizations.dart';
// import 'firebase_options.dart'; // This will be generated by flutterfire configure

final logger = Logger(
  printer: PrettyPrinter(methodCount: 2, colors: true, printTime: true),
);

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Set premium system UI overlay
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.light,
      systemNavigationBarColor: Colors.white,
      systemNavigationBarIconBrightness: Brightness.dark,
    ),
  );

  await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);

  try {
    await Hive.initFlutter();
    await RwandaLocation.initialize();

    // Safely initialize Firebase
    try {
      // Once you run 'flutterfire configure', uncomment the options below:
      await Firebase.initializeApp(
        // options: DefaultFirebaseOptions.currentPlatform,
      );
      logger.i('🚀 Firebase Integrated Successfully');
    } catch (e) {
      logger.w('⚠️ Firebase setup pending: Run flutterfire configure');
    }

    runApp(const ProviderScope(child: EKiminaApp()));
  } catch (e, stackTrace) {
    logger.e('❌ Fatal Error', error: e, stackTrace: stackTrace);
    runApp(const ProviderScope(child: ErrorApp()));
  }
}

class EKiminaApp extends ConsumerWidget {
  const EKiminaApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = AppRouter.router(ref);
    final language = ref.watch(languageProvider);

    return MaterialApp.router(
      title: 'E-Kimina Rwanda',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: ThemeMode.system,
      locale: Locale(language),
      supportedLocales: const [Locale('rw'), Locale('en')],
      localizationsDelegates: const [
        RwMaterialLocalizationsDelegate(),
        RwCupertinoLocalizationsDelegate(),
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      routerConfig: router,
    );
  }
}

class ErrorApp extends StatelessWidget {
  const ErrorApp({super.key});
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: Scaffold(body: Center(child: Text('App Error - Please restart'))));
  }
}
